name: Deploy App

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: kugert
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push
        run: |
          cd ${{ matrix.service }}
          docker build -t yourdockerhub/${{ matrix.service }}:latest .
          docker push yourdockerhub/${{ matrix.service }}:latest
        if: contains(github.event.head_commit.message, matrix.service)

