name: Deploy App

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_CLASSIC }}

      - name: Build and push image to GHCR
        if: contains(github.event.head_commit.message, matrix.service)
        run: |
          cd ${{ matrix.service }}
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:latest .
          docker push ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:latest

